/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ViewMatch,
  ViewMatchDetails,
} from '../models/index';
import {
    ViewMatchFromJSON,
    ViewMatchToJSON,
    ViewMatchDetailsFromJSON,
    ViewMatchDetailsToJSON,
} from '../models/index';

export interface MmrMatchesPostRequest {
    match: ViewMatch;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get all matches
     * Get matches
     */
    async mmrMatchesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ViewMatchDetails>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/mmr/matches`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ViewMatchDetailsFromJSON));
    }

    /**
     * Get all matches
     * Get matches
     */
    async mmrMatchesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ViewMatchDetails>> {
        const response = await this.mmrMatchesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit a match for MMR calculation
     * Submit a match
     */
    async mmrMatchesPostRaw(requestParameters: MmrMatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['match'] == null) {
            throw new runtime.RequiredError(
                'match',
                'Required parameter "match" was null or undefined when calling mmrMatchesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mmr/matches`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ViewMatchToJSON(requestParameters['match']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Submit a match for MMR calculation
     * Submit a match
     */
    async mmrMatchesPost(requestParameters: MmrMatchesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mmrMatchesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
