/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MmrMatch,
} from '../models/index';
import {
    MmrMatchFromJSON,
    MmrMatchToJSON,
} from '../models/index';

export interface MmrMatchPostRequest {
    match: MmrMatch;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Submit a match for MMR calculation
     * Submit a match
     */
    async mmrMatchPostRaw(requestParameters: MmrMatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['match'] == null) {
            throw new runtime.RequiredError(
                'match',
                'Required parameter "match" was null or undefined when calling mmrMatchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/mmr/match`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MmrMatchToJSON(requestParameters['match']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Submit a match for MMR calculation
     * Submit a match
     */
    async mmrMatchPost(requestParameters: MmrMatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.mmrMatchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
