/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReposLeaderboardEntry,
} from '../models/index';
import {
    ReposLeaderboardEntryFromJSON,
    ReposLeaderboardEntryToJSON,
} from '../models/index';

/**
 * 
 */
export class LeaderboardApi extends runtime.BaseAPI {

    /**
     * Get leaderboard stats including wins, loses, and MMR of users
     * Get leaderboard stats
     */
    async v1StatsLeaderboardGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReposLeaderboardEntry>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/stats/leaderboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReposLeaderboardEntryFromJSON));
    }

    /**
     * Get leaderboard stats including wins, loses, and MMR of users
     * Get leaderboard stats
     */
    async v1StatsLeaderboardGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReposLeaderboardEntry>> {
        const response = await this.v1StatsLeaderboardGetRaw(initOverrides);
        return await response.value();
    }

}
