/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ViewClaimUser,
  ViewProfileDetails,
} from '../models/index';
import {
    ViewClaimUserFromJSON,
    ViewClaimUserToJSON,
    ViewProfileDetailsFromJSON,
    ViewProfileDetailsToJSON,
} from '../models/index';

export interface V1ProfileClaimPostRequest {
    user: ViewClaimUser;
}

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Claims a user by ID
     * Claim user
     */
    async v1ProfileClaimPostRaw(requestParameters: V1ProfileClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ViewProfileDetails>> {
        if (requestParameters['user'] == null) {
            throw new runtime.RequiredError(
                'user',
                'Required parameter "user" was null or undefined when calling v1ProfileClaimPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/profile/claim`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ViewClaimUserToJSON(requestParameters['user']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ViewProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Claims a user by ID
     * Claim user
     */
    async v1ProfileClaimPost(requestParameters: V1ProfileClaimPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ViewProfileDetails> {
        const response = await this.v1ProfileClaimPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get profile details of the authenticated user
     * Get profile
     */
    async v1ProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ViewProfileDetails>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v1/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ViewProfileDetailsFromJSON(jsonValue));
    }

    /**
     * Get profile details of the authenticated user
     * Get profile
     */
    async v1ProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ViewProfileDetails> {
        const response = await this.v1ProfileGetRaw(initOverrides);
        return await response.value();
    }

}
