/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ViewPlayerHistoryDetails,
} from '../models/index';
import {
    ViewPlayerHistoryDetailsFromJSON,
    ViewPlayerHistoryDetailsToJSON,
} from '../models/index';

export interface StatsPlayerHistoryGetRequest {
    userId?: number;
    start?: string;
    end?: string;
}

/**
 * 
 */
export class StatisticsApi extends runtime.BaseAPI {

    /**
     * Get player history including MMR and date
     * Get player history
     */
    async statsPlayerHistoryGetRaw(requestParameters: StatsPlayerHistoryGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ViewPlayerHistoryDetails>>> {
        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stats/player-history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ViewPlayerHistoryDetailsFromJSON));
    }

    /**
     * Get player history including MMR and date
     * Get player history
     */
    async statsPlayerHistoryGet(requestParameters: StatsPlayerHistoryGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ViewPlayerHistoryDetails>> {
        const response = await this.statsPlayerHistoryGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
