/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ViewUserDetails,
} from '../models/index';
import {
    ViewUserDetailsFromJSON,
    ViewUserDetailsToJSON,
} from '../models/index';

export interface SearchGetRequest {
    query: string;
}

/**
 * 
 */
export class UsersApi extends runtime.BaseAPI {

    /**
     * Searches users by name
     * Search users
     */
    async searchGetRaw(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ViewUserDetails>>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ViewUserDetailsFromJSON));
    }

    /**
     * Searches users by name
     * Search users
     */
    async searchGet(requestParameters: SearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ViewUserDetails>> {
        const response = await this.searchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
