ARG GO_VERSION=1
FROM golang:${GO_VERSION}-bookworm AS builder

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

RUN go install github.com/bokwoon95/wgo@latest

RUN curl -sSf https://atlasgo.sh | sh

CMD ["wgo", "run", "main.go"]

EXPOSE 8080