/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MmrMatchTeam } from './MmrMatchTeam';
import {
    MmrMatchTeamFromJSON,
    MmrMatchTeamFromJSONTyped,
    MmrMatchTeamToJSON,
} from './MmrMatchTeam';

/**
 * 
 * @export
 * @interface MmrMatch
 */
export interface MmrMatch {
    /**
     * 
     * @type {MmrMatchTeam}
     * @memberof MmrMatch
     */
    team1: MmrMatchTeam;
    /**
     * 
     * @type {MmrMatchTeam}
     * @memberof MmrMatch
     */
    team2: MmrMatchTeam;
}

/**
 * Check if a given object implements the MmrMatch interface.
 */
export function instanceOfMmrMatch(value: object): boolean {
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function MmrMatchFromJSON(json: any): MmrMatch {
    return MmrMatchFromJSONTyped(json, false);
}

export function MmrMatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): MmrMatch {
    if (json == null) {
        return json;
    }
    return {
        
        'team1': MmrMatchTeamFromJSON(json['team1']),
        'team2': MmrMatchTeamFromJSON(json['team2']),
    };
}

export function MmrMatchToJSON(value?: MmrMatch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1': MmrMatchTeamToJSON(value['team1']),
        'team2': MmrMatchTeamToJSON(value['team2']),
    };
}

