/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReposLeaderboardEntry
 */
export interface ReposLeaderboardEntry {
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    loses?: number;
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    losingStreak?: number;
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    mmr?: number;
    /**
     * 
     * @type {string}
     * @memberof ReposLeaderboardEntry
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    winningStreak?: number;
    /**
     * 
     * @type {number}
     * @memberof ReposLeaderboardEntry
     */
    wins?: number;
}

/**
 * Check if a given object implements the ReposLeaderboardEntry interface.
 */
export function instanceOfReposLeaderboardEntry(value: object): boolean {
    return true;
}

export function ReposLeaderboardEntryFromJSON(json: any): ReposLeaderboardEntry {
    return ReposLeaderboardEntryFromJSONTyped(json, false);
}

export function ReposLeaderboardEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReposLeaderboardEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'loses': json['loses'] == null ? undefined : json['loses'],
        'losingStreak': json['losingStreak'] == null ? undefined : json['losingStreak'],
        'mmr': json['mmr'] == null ? undefined : json['mmr'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'winningStreak': json['winningStreak'] == null ? undefined : json['winningStreak'],
        'wins': json['wins'] == null ? undefined : json['wins'],
    };
}

export function ReposLeaderboardEntryToJSON(value?: ReposLeaderboardEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'loses': value['loses'],
        'losingStreak': value['losingStreak'],
        'mmr': value['mmr'],
        'name': value['name'],
        'userId': value['userId'],
        'winningStreak': value['winningStreak'],
        'wins': value['wins'],
    };
}

