/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewMatchTeamV2 } from './ViewMatchTeamV2';
import {
    ViewMatchTeamV2FromJSON,
    ViewMatchTeamV2FromJSONTyped,
    ViewMatchTeamV2ToJSON,
} from './ViewMatchTeamV2';

/**
 * 
 * @export
 * @interface ViewMatchV2
 */
export interface ViewMatchV2 {
    /**
     * 
     * @type {ViewMatchTeamV2}
     * @memberof ViewMatchV2
     */
    team1: ViewMatchTeamV2;
    /**
     * 
     * @type {ViewMatchTeamV2}
     * @memberof ViewMatchV2
     */
    team2: ViewMatchTeamV2;
}

/**
 * Check if a given object implements the ViewMatchV2 interface.
 */
export function instanceOfViewMatchV2(value: object): boolean {
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function ViewMatchV2FromJSON(json: any): ViewMatchV2 {
    return ViewMatchV2FromJSONTyped(json, false);
}

export function ViewMatchV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewMatchV2 {
    if (json == null) {
        return json;
    }
    return {
        
        'team1': ViewMatchTeamV2FromJSON(json['team1']),
        'team2': ViewMatchTeamV2FromJSON(json['team2']),
    };
}

export function ViewMatchV2ToJSON(value?: ViewMatchV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1': ViewMatchTeamV2ToJSON(value['team1']),
        'team2': ViewMatchTeamV2ToJSON(value['team2']),
    };
}

