/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewMatchTeam } from './ViewMatchTeam';
import {
    ViewMatchTeamFromJSON,
    ViewMatchTeamFromJSONTyped,
    ViewMatchTeamToJSON,
} from './ViewMatchTeam';

/**
 * 
 * @export
 * @interface ViewMatchDetails
 */
export interface ViewMatchDetails {
    /**
     * 
     * @type {string}
     * @memberof ViewMatchDetails
     */
    date: string;
    /**
     * 
     * @type {ViewMatchTeam}
     * @memberof ViewMatchDetails
     */
    team1: ViewMatchTeam;
    /**
     * 
     * @type {ViewMatchTeam}
     * @memberof ViewMatchDetails
     */
    team2: ViewMatchTeam;
}

/**
 * Check if a given object implements the ViewMatchDetails interface.
 */
export function instanceOfViewMatchDetails(value: object): boolean {
    if (!('date' in value)) return false;
    if (!('team1' in value)) return false;
    if (!('team2' in value)) return false;
    return true;
}

export function ViewMatchDetailsFromJSON(json: any): ViewMatchDetails {
    return ViewMatchDetailsFromJSONTyped(json, false);
}

export function ViewMatchDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewMatchDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'team1': ViewMatchTeamFromJSON(json['team1']),
        'team2': ViewMatchTeamFromJSON(json['team2']),
    };
}

export function ViewMatchDetailsToJSON(value?: ViewMatchDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'team1': ViewMatchTeamToJSON(value['team1']),
        'team2': ViewMatchTeamToJSON(value['team2']),
    };
}

