/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewMatchMMRCalculationDetails
 */
export interface ViewMatchMMRCalculationDetails {
    /**
     * 
     * @type {number}
     * @memberof ViewMatchMMRCalculationDetails
     */
    team1Player1MMRDelta: number;
    /**
     * 
     * @type {number}
     * @memberof ViewMatchMMRCalculationDetails
     */
    team1Player2MMRDelta: number;
    /**
     * 
     * @type {number}
     * @memberof ViewMatchMMRCalculationDetails
     */
    team2Player1MMRDelta: number;
    /**
     * 
     * @type {number}
     * @memberof ViewMatchMMRCalculationDetails
     */
    team2Player2MMRDelta: number;
}

/**
 * Check if a given object implements the ViewMatchMMRCalculationDetails interface.
 */
export function instanceOfViewMatchMMRCalculationDetails(value: object): boolean {
    if (!('team1Player1MMRDelta' in value)) return false;
    if (!('team1Player2MMRDelta' in value)) return false;
    if (!('team2Player1MMRDelta' in value)) return false;
    if (!('team2Player2MMRDelta' in value)) return false;
    return true;
}

export function ViewMatchMMRCalculationDetailsFromJSON(json: any): ViewMatchMMRCalculationDetails {
    return ViewMatchMMRCalculationDetailsFromJSONTyped(json, false);
}

export function ViewMatchMMRCalculationDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewMatchMMRCalculationDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'team1Player1MMRDelta': json['team1Player1MMRDelta'],
        'team1Player2MMRDelta': json['team1Player2MMRDelta'],
        'team2Player1MMRDelta': json['team2Player1MMRDelta'],
        'team2Player2MMRDelta': json['team2Player2MMRDelta'],
    };
}

export function ViewMatchMMRCalculationDetailsToJSON(value?: ViewMatchMMRCalculationDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'team1Player1MMRDelta': value['team1Player1MMRDelta'],
        'team1Player2MMRDelta': value['team1Player2MMRDelta'],
        'team2Player1MMRDelta': value['team2Player1MMRDelta'],
        'team2Player2MMRDelta': value['team2Player2MMRDelta'],
    };
}

