/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewUserDetails
 */
export interface ViewUserDetails {
    /**
     * 
     * @type {string}
     * @memberof ViewUserDetails
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewUserDetails
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ViewUserDetails
     */
    userId: number;
}

/**
 * Check if a given object implements the ViewUserDetails interface.
 */
export function instanceOfViewUserDetails(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function ViewUserDetailsFromJSON(json: any): ViewUserDetails {
    return ViewUserDetailsFromJSONTyped(json, false);
}

export function ViewUserDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewUserDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function ViewUserDetailsToJSON(value?: ViewUserDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
        'name': value['name'],
        'userId': value['userId'],
    };
}

