/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewMatchTeam
 */
export interface ViewMatchTeam {
    /**
     * 
     * @type {string}
     * @memberof ViewMatchTeam
     */
    member1: string;
    /**
     * 
     * @type {string}
     * @memberof ViewMatchTeam
     */
    member2: string;
    /**
     * 
     * @type {number}
     * @memberof ViewMatchTeam
     */
    score: number;
}

/**
 * Check if a given object implements the ViewMatchTeam interface.
 */
export function instanceOfViewMatchTeam(value: object): boolean {
    if (!('member1' in value)) return false;
    if (!('member2' in value)) return false;
    if (!('score' in value)) return false;
    return true;
}

export function ViewMatchTeamFromJSON(json: any): ViewMatchTeam {
    return ViewMatchTeamFromJSONTyped(json, false);
}

export function ViewMatchTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewMatchTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'member1': json['member1'],
        'member2': json['member2'],
        'score': json['score'],
    };
}

export function ViewMatchTeamToJSON(value?: ViewMatchTeam | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'member1': value['member1'],
        'member2': value['member2'],
        'score': value['score'],
    };
}

