/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewProfileDetails
 */
export interface ViewProfileDetails {
    /**
     * 
     * @type {number}
     * @memberof ViewProfileDetails
     */
    userId?: number;
}

/**
 * Check if a given object implements the ViewProfileDetails interface.
 */
export function instanceOfViewProfileDetails(value: object): boolean {
    return true;
}

export function ViewProfileDetailsFromJSON(json: any): ViewProfileDetails {
    return ViewProfileDetailsFromJSONTyped(json, false);
}

export function ViewProfileDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewProfileDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ViewProfileDetailsToJSON(value?: ViewProfileDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

