/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewClaimUser
 */
export interface ViewClaimUser {
    /**
     * 
     * @type {number}
     * @memberof ViewClaimUser
     */
    userId: number;
}

/**
 * Check if a given object implements the ViewClaimUser interface.
 */
export function instanceOfViewClaimUser(value: object): boolean {
    if (!('userId' in value)) return false;
    return true;
}

export function ViewClaimUserFromJSON(json: any): ViewClaimUser {
    return ViewClaimUserFromJSONTyped(json, false);
}

export function ViewClaimUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewClaimUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function ViewClaimUserToJSON(value?: ViewClaimUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
    };
}

