/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewPlayerHistoryDetails
 */
export interface ViewPlayerHistoryDetails {
    /**
     * 
     * @type {string}
     * @memberof ViewPlayerHistoryDetails
     */
    date: string;
    /**
     * 
     * @type {number}
     * @memberof ViewPlayerHistoryDetails
     */
    mmr: number;
    /**
     * 
     * @type {string}
     * @memberof ViewPlayerHistoryDetails
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ViewPlayerHistoryDetails
     */
    userId: number;
}

/**
 * Check if a given object implements the ViewPlayerHistoryDetails interface.
 */
export function instanceOfViewPlayerHistoryDetails(value: object): boolean {
    if (!('date' in value)) return false;
    if (!('mmr' in value)) return false;
    if (!('name' in value)) return false;
    if (!('userId' in value)) return false;
    return true;
}

export function ViewPlayerHistoryDetailsFromJSON(json: any): ViewPlayerHistoryDetails {
    return ViewPlayerHistoryDetailsFromJSONTyped(json, false);
}

export function ViewPlayerHistoryDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewPlayerHistoryDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'mmr': json['mmr'],
        'name': json['name'],
        'userId': json['userId'],
    };
}

export function ViewPlayerHistoryDetailsToJSON(value?: ViewPlayerHistoryDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'],
        'mmr': value['mmr'],
        'name': value['name'],
        'userId': value['userId'],
    };
}

