/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewCreateUser
 */
export interface ViewCreateUser {
    /**
     * 
     * @type {string}
     * @memberof ViewCreateUser
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof ViewCreateUser
     */
    name: string;
}

/**
 * Check if a given object implements the ViewCreateUser interface.
 */
export function instanceOfViewCreateUser(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function ViewCreateUserFromJSON(json: any): ViewCreateUser {
    return ViewCreateUserFromJSONTyped(json, false);
}

export function ViewCreateUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewCreateUser {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'name': json['name'],
    };
}

export function ViewCreateUserToJSON(value?: ViewCreateUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
        'name': value['name'],
    };
}

