/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewTimeStatisticsEntry
 */
export interface ViewTimeStatisticsEntry {
    /**
     * 
     * @type {number}
     * @memberof ViewTimeStatisticsEntry
     */
    count: number;
    /**
     * 0-6, 0 is Sunday
     * @type {number}
     * @memberof ViewTimeStatisticsEntry
     */
    dayOfWeek: number;
    /**
     * 0-23
     * @type {number}
     * @memberof ViewTimeStatisticsEntry
     */
    hourOfDay: number;
}

/**
 * Check if a given object implements the ViewTimeStatisticsEntry interface.
 */
export function instanceOfViewTimeStatisticsEntry(value: object): boolean {
    if (!('count' in value)) return false;
    if (!('dayOfWeek' in value)) return false;
    if (!('hourOfDay' in value)) return false;
    return true;
}

export function ViewTimeStatisticsEntryFromJSON(json: any): ViewTimeStatisticsEntry {
    return ViewTimeStatisticsEntryFromJSONTyped(json, false);
}

export function ViewTimeStatisticsEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewTimeStatisticsEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'dayOfWeek': json['dayOfWeek'],
        'hourOfDay': json['hourOfDay'],
    };
}

export function ViewTimeStatisticsEntryToJSON(value?: ViewTimeStatisticsEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'dayOfWeek': value['dayOfWeek'],
        'hourOfDay': value['hourOfDay'],
    };
}

