// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mmr/matches": {
            "get": {
                "description": "Get all matches",
                "produces": [
                    "application/json"
                ],
                "summary": "Get matches",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/view.MatchDetails"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Submit a match for MMR calculation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Submit a match",
                "parameters": [
                    {
                        "description": "Match object",
                        "name": "match",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/view.Match"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "match submitted",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stats/leaderboard": {
            "get": {
                "description": "Get leaderboard stats including wins, loses, and MMR of users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leaderboard"
                ],
                "summary": "Get leaderboard stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/repos.LeaderboardEntry"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "repos.LeaderboardEntry": {
            "type": "object",
            "properties": {
                "loses": {
                    "type": "integer"
                },
                "mmr": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "view.Match": {
            "type": "object",
            "required": [
                "team1",
                "team2"
            ],
            "properties": {
                "team1": {
                    "$ref": "#/definitions/view.MatchTeam"
                },
                "team2": {
                    "$ref": "#/definitions/view.MatchTeam"
                }
            }
        },
        "view.MatchDetails": {
            "type": "object",
            "required": [
                "date",
                "team1",
                "team2"
            ],
            "properties": {
                "date": {
                    "type": "string"
                },
                "team1": {
                    "$ref": "#/definitions/view.MatchTeam"
                },
                "team2": {
                    "$ref": "#/definitions/view.MatchTeam"
                }
            }
        },
        "view.MatchTeam": {
            "type": "object",
            "required": [
                "member1",
                "member2",
                "score"
            ],
            "properties": {
                "member1": {
                    "type": "string"
                },
                "member2": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
