name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - "backend/**/*"

concurrency:
  group: deploy-group # optional: ensure only one action runs at a time

jobs:
  migrations_lint:
    services:
      # Spin up a postgres:15 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --depth=1 origin main
      - uses: ariga/setup-atlas@v0
      - run: |
          atlas version
        name: Check Atlas CLI version
        working-directory: ./backend
      - run: |
          atlas migrate lint --env gorm --git-base origin/main
        name: Lint
        working-directory: ./backend
  migrations_apply:
    name: Migrate database
    runs-on: ubuntu-latest
    needs: migrations_lint
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - run: |
          atlas version
        name: Check Atlas CLI version
        working-directory: ./backend
      - run: |
          atlas migrate apply --env gorm --revisions-schema public --url ${{ secrets.DATABASE_URL }}
        name: Apply migrations
        working-directory: ./backend
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: migrations_apply
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
