name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - "backend-dotnet/**/*"

concurrency:
  group: deploy-group # optional: ensure only one action runs at a time

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: migrations_apply
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        working-directory: ./backend-dotnet
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
