name: Deploy backend
on:
  push:
    branches:
      - main
    paths:
      - "backend/**/*"

concurrency:
  group: deploy-group # optional: ensure only one action runs at a time

jobs:
  # TODO: Fix this job to actually deploy go backend to a server.
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
